#!/usr/bin/env python3
"""Generates apps/authd/passphrase_common.c from a PINNED common-password list.

Usage: gen_passphrase_common.py <xato-net-10-million-passwords-10000.txt> <out.c>

Source (V4-13c): SecLists, Passwords/Common-Credentials/
xato-net-10-million-passwords-10000.txt at commit
49c9fcd20e0945f24ec854872f265eb3d13c3741, MIT-licensed. The input's SHA-256
is checked before anything is written: a substituted list would change what
the passphrase policy refuses, silently. The generated file is committed, so
building never needs the network; this script exists so the table can be
regenerated -- and re-verified -- by anyone.

Normalisation, so the C side can binary-search: lower-cased, entries shorter
than 4 bytes dropped (they would only ever match as whole passwords, and every
such passphrase is already refused for length), duplicates removed, sorted
bytewise.
"""
import hashlib, sys, pathlib

PINNED_SHA256 = "c63d5e4ccc31344d662583cc39ca4bd5bd20517ff1d24501f0c4e0c22d9b722a"
COMMIT = "49c9fcd20e0945f24ec854872f265eb3d13c3741"

src, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
raw = src.read_bytes()
got = hashlib.sha256(raw).hexdigest()
if got != PINNED_SHA256:
    sys.exit(f"refusing: {src} has SHA-256 {got}, pinned {PINNED_SHA256}")

words = set()
for line in raw.decode("ascii").splitlines():
    w = line.strip().lower()
    if len(w) >= 4:
        words.add(w)
words = sorted(words, key=lambda w: w.encode())

def c_str(w):
    return '"' + w.replace("\\", "\\\\").replace('"', '\\"').replace("?", "\\?") + '"'

MIT = """Copyright (c) 2018 Daniel Miessler

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."""

lines = [
    "/* GENERATED by tools/gen_passphrase_common.py -- do not edit.",
    " *",
    " * The common-password list the passphrase policy refuses (V4-13c):",
    " * SecLists, Passwords/Common-Credentials/xato-net-10-million-passwords-10000.txt",
    f" * at commit {COMMIT},",
    f" * SHA-256 {PINNED_SHA256}.",
    f" * {len(words)} entries after normalisation (lower-cased, >= 4 bytes, deduplicated, sorted).",
    " *",
    " * The list is third-party data, distributed under the MIT License:",
    " *",
] + [(" * " + l).rstrip() for l in MIT.splitlines()] + [
    " */",
    '#include "passphrase.h"',
    "",
    f"const size_t pp_common_count = {len(words)}u;",
    "const char *const pp_common[] = {",
]
for w in words:
    lines.append(f"    {c_str(w)},")
lines += ["};", ""]
out.write_text("\n".join(lines))
print(f"wrote {out}: {len(words)} entries")
